import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { SYMPTOM_KEYS, t, getLanguage } from './i18n.js';
import { getChartBase64 } from './chart.js';

function getMetadata() {
  const nameEl = document.getElementById('patient-name');
  const dateEl = document.getElementById('report-date');
  return {
    name: nameEl?.value || '',
    date: dateEl?.value || new Date().toISOString().slice(0, 10),
    language: getLanguage(),
  };
}

function buildDataMatrix(data) {
  const stages = t('stages');
  const rows = stages.map((stage, i) => {
    const row = [stage];
    SYMPTOM_KEYS.forEach((key) => {
      row.push(data[key][i]);
    });
    return row;
  });
  return rows;
}

function exportPDF(data) {
  const meta = getMetadata();
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  // Title
  doc.setFontSize(18);
  doc.setTextColor(35, 87, 135);
  doc.text(t('title'), 14, 16);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  let metaY = 24;
  if (meta.name) {
    doc.text(`${t('ui.name').replace(' (optional)', '').replace(' (vapaaehtoinen)', '')}: ${meta.name}`, 14, metaY);
    metaY += 5;
  }
  doc.text(`${t('ui.date')}: ${meta.date}`, 14, metaY);

  // Chart image
  const chartImg = getChartBase64();
  if (chartImg) {
    doc.addImage(chartImg, 'PNG', 14, metaY + 4, 180, 80);
  }

  // Data table
  const symptoms = SYMPTOM_KEYS.map((key) => t(`symptoms.${key}`));
  const stages = t('stages');
  const headers = [t('stages')[0] ? '' : 'Stage', ...symptoms];

  const body = stages.map((stage, i) => {
    const row = [stage];
    SYMPTOM_KEYS.forEach((key) => {
      const val = data[key][i];
      const sev = t('severity')[val];
      row.push(`${val} (${sev})`);
    });
    return row;
  });

  autoTable(doc, {
    startY: metaY + 88,
    head: [['Stage', ...symptoms]],
    body: body,
    theme: 'grid',
    headStyles: {
      fillColor: [35, 87, 135],
      textColor: 255,
      fontSize: 8,
    },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [248, 249, 250] },
    margin: { left: 14 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Exercise Symptom Mapper — rikhard.fi/oirekuvaaja', 14, pageHeight - 6);

  const filename = meta.name
    ? `symptoms_${meta.name.replace(/\s+/g, '_')}_${meta.date}.pdf`
    : `symptoms_${meta.date}.pdf`;
  doc.save(filename);
}

function exportXLSX(data) {
  const meta = getMetadata();
  const stages = t('stages');
  const symptoms = SYMPTOM_KEYS.map((key) => t(`symptoms.${key}`));

  const wsData = [
    [t('title')],
    meta.name ? [`${t('ui.name')}: ${meta.name}`] : [],
    [`${t('ui.date')}: ${meta.date}`],
    [],
    ['Stage', ...symptoms],
    ...stages.map((stage, i) => {
      const row = [stage];
      SYMPTOM_KEYS.forEach((key) => {
        row.push(data[key][i]);
      });
      return row;
    }),
  ].filter((r) => r.length > 0);

  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Set column widths
  ws['!cols'] = [
    { wch: 22 },
    ...symptoms.map(() => ({ wch: 16 })),
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Symptoms');

  const filename = meta.name
    ? `symptoms_${meta.name.replace(/\s+/g, '_')}_${meta.date}.xlsx`
    : `symptoms_${meta.date}.xlsx`;
  XLSX.writeFile(wb, filename);
}

function exportJSON(data) {
  const meta = getMetadata();
  const stages = t('stages');

  const structured = {
    version: '1.0',
    tool: 'Exercise Symptom Mapper',
    language: meta.language,
    date: meta.date,
    name: meta.name || null,
    symptoms: {},
  };

  SYMPTOM_KEYS.forEach((key) => {
    structured.symptoms[key] = {};
    stages.forEach((stage, i) => {
      structured.symptoms[key][stage] = data[key][i];
    });
  });

  const json = JSON.stringify(structured, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;

  const filename = meta.name
    ? `symptoms_${meta.name.replace(/\s+/g, '_')}_${meta.date}.json`
    : `symptoms_${meta.date}.json`;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function exportClipboard(data) {
  const meta = getMetadata();
  const stages = t('stages');
  const severity = t('severity');

  let text = `${t('title')}\n`;
  if (meta.name) text += `Name: ${meta.name}\n`;
  text += `Date: ${meta.date}\n\n`;

  SYMPTOM_KEYS.forEach((key) => {
    text += `${t(`symptoms.${key}`)}:\n`;
    stages.forEach((stage, i) => {
      const val = data[key][i];
      text += `  ${stage}: ${val} (${severity[val]})\n`;
    });
    text += '\n';
  });

  text += 'Generated by Exercise Symptom Mapper';

  return navigator.clipboard.writeText(text);
}

export { exportPDF, exportXLSX, exportJSON, exportClipboard };
